baseurl = "http://bbchen.github.io"
languageCode = "en"
title = "Zen Life"
theme = "hemingway"
copyright = "&copy; <a href=\"https://github.com/bbchen\">Zen Life</a> 2016"
disqusShortname = "zen-life"
googleAnalytics = "UA-72141705-1"

hasCJKLanguage = true
uglyurls = true

# "yaml", "toml", "json"
metaDataFormat = "yaml"
newContentEditor = "subl"

[params]

[params.highlight]
style = "github"
languages = ["go", "dockerfile"]

[[params.social]]
url = "https://github.com/bbchen"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/bbchen"
fa_icon = "fa-twitter"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"

[menu]

[[menu.main]]
    name = "About"
    pre = "<i class='fa fa-heart'></i>"
    weight = -110
    identifier = "about"
    url = "/about/"
[[menu.main]]
    name = "Contact"
    pre = "<i class='fa fa-road'></i>"
    weight = -100
    url = "/contact/"
[[menu.main]]
    name = "Now"
    pre = "<i class='fa fa-road'></i>"
    weight = -120
    url = "/now/"

[permalinks]
  post = "/posts/:year/:month/:title.html"